Run some of the processes on CORE1.
* Watchdog.
* Actuator control.
* CAN reader.

Because I have to spawn ONE task on CORE1, which can then spawn
others, this means that the Watchdog and the CAN reader tasks
start a little later than I had hoped, but in the end it shouldn't
matter.

NOTE: Unfortunately, this give a compile error:
```
error[E0277]: `*mut ()` cannot be shared between threads safely
   --> src/drive-by-wire.rs:162:9
    |
159 |       spawn_core1(
    |       ----------- required by a bound introduced by this call
...
162 | /         move || {
163 | |             let executor = EXECUTOR.init(Executor::new());
164 | |             executor.run(|spawner| {
165 | |                 spawner.spawn(unwrap!(core1_tasks(
...   |
172 | |             });
173 | |         },
    | |_________^ `*mut ()` cannot be shared between threads safely
    |
    = help: within `NoopRawMutex`, the trait `Sync` is not implemented for `*mut ()`
note: required because it appears within the type `PhantomData<*mut ()>`
   --> ....
    |
822 | pub struct PhantomData<T: PointeeSized>;
    |            ^^^^^^^^^^^
note: required because it appears within the type `NoopRawMutex`
   --> ....
    |
 70 | pub struct NoopRawMutex {
    |            ^^^^^^^^^^^^
    = note: required for `Mutex<NoopRawMutex, Flash<'static, FLASH, Async, 2097152>>` to implement `Sync`
    = note: required for `&Mutex<NoopRawMutex, Flash<'static, FLASH, Async, 2097152>>` to implement `Send`
note: required because it's used within this closure
   --> src/drive-by-wire.rs:162:9
    |
162 |         move || {
    |         ^^^^^^^
note: required by a bound in `spawn_core1`
   --> ....
    |
161 | pub fn spawn_core1<F, const SIZE: usize>(_core1: Peri<'static, CORE1>, stack: &'static mut Stack<SIZE>, entry: F)
    |        ----------- required by a bound in this function
162 | where
163 |     F: FnOnce() -> bad::Never + Send + 'static,
    |                                 ^^^^ required by this bound in `spawn_core1`
    = note: the full name for the type has been written to '....'
    = note: consider using `--verbose` to print the full type name to the console

For more information about this error, try `rustc --explain E0277`.
error: could not compile `drive-by-wire` (bin "drive-by-wire") due to 1 previous error
```

I've asked about that on the Rust forum:
    https://users.rust-lang.org/t/multiple-tasks-processes-on-core1/137731